package server.entity.habit.energy.subcategory;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Object used to retrieve data from client requests.
 * This object contains all attributes to create and
 * calculate a SolarPanel entity.
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class SolarPanelForm {

    /**
     * Number of hours active.
     */
    private double hours;

    /**
     * Amount of watt generated by one solar panel.
     */
    private int watt;

    /**
     * Amount of solar panels.
     */
    private int numberOfSolarPanels;
}
