package server.entity.habit.energy.subcategory;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import server.entity.habit.energy.Energy;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SolarPanel entity which corresponds to 'solar_panels' table in DB.
 */
@Entity
@Table(name = "solar_panels")
@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class SolarPanel extends Energy {

    /**
     * Amount of watt generated by one solar panel.
     */
    private int watt;

    /**
     * Amount of solar panels.
     */
    @Column(name = "number_of_solar_panels")
    private int numberOfSolarPanels;
}
